version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: courses_postgres
    environment:
      - POSTGRES_DB=courses_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" 
    restart: unless-stopped

  api:
    container_name: courses_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=courses_db;Username=user;Password=password
    depends_on:
      - db
    restart: on-failure

volumes:
  postgres_data: